piVersion: apps/v1
kind: Deployment
metadata: 
  name: apache-deployment
  labels:
    app: apache
  annotations:
    kubernetes.io/change-cause: "Version 1"
spec: 
  replicas: 6
  minReadySeconds: 10
  strategy: 
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels: 
      app: apache
  template: 
    metadata: 
      labels:
        app: apache
    spec:
      containers:
      - name: apache 
        image: vaibhs123/flask
        ports:
        - containerPort: 80
